# Generated by Django 2.1.5 on 2020-06-22 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('productName', models.CharField(max_length=100)),
                ('userName', models.CharField(max_length=50)),
                ('userEmail', models.EmailField(max_length=254)),
                ('userAddress', models.CharField(max_length=255)),
            ],
        ),
    ]
